### PR TITLE
fix(bindings): improve identity error handling

### LINKED ISSUE #1035: Node panics instead of returning error when shared_secret is invalid
## Summary

The data-plane node crashes with a panic when an invalid `shared_secret` is provided (e.g., less than 32 characters). Instead of panicking, the node should gracefully handle the error and report it to the caller.

## Current Behavior

When a shared secret shorter than 32 characters is provided, the node panics:

```
thread '<unnamed>' panicked at core/auth/src/shared_secret.rs:185:46:
invalid shared_secret: TokenInvalid("shared_secret too short (min 32 chars)")
```

The panic occurs because `SharedSecret::new()` uses `.expect()` on the validation result:

```rust
// data-plane/core/auth/src/shared_secret.rs:185
Self::validate_secret(shared_secret).expect("invalid shared_secret");
```

## Expected Behavior

The node should:
1. **Not panic** on invalid configuration
2. Return a proper error to the caller indicating the configuration issue
3. Allow the caller to handle the error gracefully (e.g., log and reject the request, or fail startup with a clear error message)

## Proposed Solution

Change `SharedSecret::new()` to return a `Result<Self, AuthError>` instead of panicking:

```rust
// Before
pub fn new(id: &str, shared_secret: &str) -> Self {
    Self::validate_id(id).expect("invalid id");
    Self::validate_secret(shared_secret).expect("invalid shared_secret");
    // ...
}

// After
pub fn new(id: &str, shared_secret: &str) -> Result<Self, AuthError> {
    Self::validate_id(id)?;
    Self::validate_secret(shared_secret)?;
    // ...
    Ok(SharedSecret(Arc::new(internal)))
}
```

This will require updating all call sites to handle the `Result`, but provides proper error propagation.

## Impact

- **Security**: Panics can be exploited for denial-of-service attacks
- **Reliability**: Production nodes should never crash due to configuration errors
- **Usability**: Clear error messages help operators diagnose configuration issues

## Location

- **File**: `data-plane/core/auth/src/shared_secret.rs`
- **Line**: 185-186 (and similar `.expect()` calls)

### PR DESCRIPTION
**Pull request by msardara**
# Description

Changed `SharedSecret::new()` to return `Result<Self, AuthError>`
instead of panicking on validation errors, and converted Python bindings
from `From` to `TryFrom` to properly surface validation errors as Python
exceptions. This eliminates panics across the FFI boundary and provides
type-safe error handling throughout the stack.

Fixes #1035 

## Type of Change

- [x] Bugfix
- [ ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](/agntcy/repo-template/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [x] New code contribution is covered by automated tests
- [x] All new and existing tests pass

### CODE REVIEW

File: data-plane/python/bindings/src/pyidentity.rs [hunk 1]
```diff
@@ -364,14 +370,14 @@ impl From<PyIdentityProvider> for IdentityProvider {
...
                 }
                 #[cfg(target_family = "windows")]
                 {
                     let _ = (socket_path, target_spiffe_id, jwt_audiences);
-                    panic!(
-                        "SPIRE identity provider is not supported on Windows. SPIRE requires Unix domain sockets which are not available on Windows platforms."
-                    );
+                    Err(AuthError::TokenInvalid(
+                        "SPIRE identity provider is not supported on Windows. SPIRE requires Unix domain sockets which are not available on Windows platforms.".to_string()
+                    ))
```
Comment (micpapal) [inline data-plane/python/bindings/src/pyidentity.rs]: maybe you can use a const str since the same error is also returned at line 609

**Review by micpapal — APPROVED** [review]
