### PR TITLE
fix(session): correctly remove routes on session close

### LINKED ISSUE #1033: Correctly remove routes on session close
When a session closes, both the moderator and participant remove all subscriptions and routes to the remote node and group. This causes issues when multiple sessions depend on the same entry in the forwarding table. If one session closes while another is still active, the remaining session will fail because the required state is no longer available to support it.

### PR DESCRIPTION
**Pull request by micpapal**
# Description

This PR fixes session route cleanup so that routes are correctly removed when sessions close. In particular the fix introduces a ref count for each route so that if multiple sessions use the same route, the route is removed only if the ref count goes to 0.

The PR improves the testing for P2P application to test 2 sessions in parallel.

fix #1033

## Type of Change

- [x] Bugfix
- [ ] New Feature
- [ ] Breaking Change
- [ ] Refactor
- [ ] Documentation
- [ ] Other (please describe)

## Checklist

- [x] I have read the [contributing guidelines](/agntcy/repo-template/blob/main/CONTRIBUTING.md)
- [x] Existing issues have been referenced (where applicable)
- [x] I have verified this change is not present in other open pull requests
- [x] Functionality is documented
- [x] All code style checks pass
- [x] New code contribution is covered by automated tests
- [x] All new and existing tests pass

### CODE REVIEW

File: data-plane/core/session/src/session_routes.rs [hunk 1]
```diff
@@ -0,0 +1,392 @@
+// Copyright AGNTCY Contributors (https://github.com/agntcy)
+// SPDX-License-Identifier: Apache-2.0
+
+use parking_lot::RwLock;
+use slim_datapath::messages::Name;
+use std::collections::HashMap;
+use std::sync::Arc;
+
+// each route is compose by a name and the related connection id
```
Comment (msardara) [inline data-plane/core/session/src/session_routes.rs]:
```suggestion
// each route is composed by a name and the related connection id
```

File: data-plane/core/session/src/session_routes.rs [hunk 2]
```diff
@@ -0,0 +1,392 @@
...
+// this allows as to distinguish between multiple routes to the same name.
```
Comment (msardara) [inline data-plane/core/session/src/session_routes.rs]:
```suggestion
// this allows us to distinguish between multiple routes to the same name.
```

**Review by msardara — APPROVED** [review]
LGTM
